"""empty message

Revision ID: d5b73e54bc06
Revises: 3387d137f0d0
Create Date: 2023-02-10 22:51:06.966202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5b73e54bc06'
down_revision = '3387d137f0d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('park', sa.Column('addresses', sa.ARRAY(sa.JSON()), nullable=True))
    op.add_column('park', sa.Column('fees', sa.ARRAY(sa.JSON()), nullable=True))
    op.add_column('park', sa.Column('images', sa.ARRAY(sa.JSON()), nullable=True))
    op.add_column('park', sa.Column('operating_hours', sa.ARRAY(sa.JSON()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('park', 'operating_hours')
    op.drop_column('park', 'images')
    op.drop_column('park', 'fees')
    op.drop_column('park', 'addresses')
    # ### end Alembic commands ###
